CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(40) NOT NULL,
    email VARCHAR(120) NOT NULL,
    password VARCHAR(120) NOT NULL,
    nickname VARCHAR(40) NOT NULL,
    student_no VARCHAR(40),
    campus VARCHAR(40),
    phone VARCHAR(40),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE products (
    id BIGINT NOT NULL AUTO_INCREMENT,
    seller_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    category VARCHAR(60) NOT NULL,
    condition_text VARCHAR(60),
    image_urls VARCHAR(1200),
    trade_location VARCHAR(120),
    status VARCHAR(20) NOT NULL,
    view_count INT NOT NULL DEFAULT 0,
    favorite_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_products_seller (seller_id),
    KEY idx_products_status_category_created (status, category, created_at),
    KEY idx_products_hot (status, favorite_count, view_count, created_at),
    CONSTRAINT fk_products_seller FOREIGN KEY (seller_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE trade_orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_no VARCHAR(40) NOT NULL,
    product_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    meet_location VARCHAR(120),
    remark VARCHAR(500),
    confirmed_at DATETIME,
    completed_at DATETIME,
    cancelled_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_orders_order_no (order_no),
    KEY idx_trade_orders_product_status (product_id, status),
    KEY idx_trade_orders_buyer_created (buyer_id, created_at),
    KEY idx_trade_orders_seller_created (seller_id, created_at),
    CONSTRAINT fk_trade_orders_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_trade_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users (id),
    CONSTRAINT fk_trade_orders_seller FOREIGN KEY (seller_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
